package hr.unizg.foi.chorlist

// User constraints
const val ALLOWED_PASSWORD_SIZE = 5

// Intents
const val INTENT_SHOPPING_LIST_ID = "ID"
const val INTENT_SHOPPING_LIST_NAME = "SHOPPING_LIST_NAME"

// Fragments
const val SEARCH_ITEMS_FRAGMENT_TAG = "SEARCH_ITEMS_FRAGMENT_TAG"

// Shared preferences
const val AUTH_SHARED_PREFERENCES = "AUTH_SP"
const val AUTH_USERNAME = "AUTH_SP_USERNAME"
const val AUTH_PASSWORD = "AUTH_SP_PASSWORD"
const val WIDGET_SHARED_PREFERENCES = "WIDGET_SHARED_PREFERENCES"
const val WIDGET_LIST_ID = "WIDGET_LIST_ID"
const val WIDGET_LIST_NAME = "WIDGET_LIST_NAME"
const val TOAST_ADDED_TO_LIST = "Shopping list added to widget."

// Home activity design
const val UPDATE_SHOPPING_LIST_BUTTON_RIGHT_MARGIN_OFFSET = 1.5
const val UPDATE_SHOPPING_LIST_BUTTON_BOTTOM_MARGIN_OFFSET = 1.5

const val ADD_SHOPPING_LIST_BUTTON_RIGHT_MARGIN_OFFSET = 1.7
const val ADD_SHOPPING_LIST_BUTTON_BOTTOM_MARGIN_OFFSET = 0.25

// PDF settings
const val PDF_SHOPPING_LIST_BUTTON_RIGHT_MARGIN_OFFSET = 0.25
const val PDF_SHOPPING_LIST_BUTTON_BOTTOM_MARGIN_OFFSET = 1.7

const val PERMISSION_CODE = 101

// API settings
const val BASE_URL = "http://10.0.2.2:3000/api/"
